name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.0
      with:
        version: ^5.5.4
    - name: install
      run: pnpm install
    - name: build
      run: pnpm run build
    - name: lint
      run: pnpm run lint
    - name: run unit tests
      run: pnpm test
    - name: upload code coverage to codecov
      uses: codecov/codecov-action@v1

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.0
      with:
        version: ^5.5.4
    - name: install
      run: pnpm install
    - name: build
      run: pnpm run build
    - name: set git credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: set npm credentials
      run: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN > ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: publish
      run: npm publish --set-access-level public
